export default {

    tamweeny: 'تمويني',
    skip: 'تخطي',
    confirmed: 'تاكيد الطلب',
    onTheWay: 'الطلب في الطريق',
    delivered: 'تم التوصيل',
    clickHere: 'اضغط هنا',
    skip1Msg: 'سجل الدخول بسهولة',
    skip2Msg: 'تصفح المنتجات وقم بالطلب',
    skip3Msg: 'تابع طلبك حتي يصل لباب المنزل',
    skip1BelowMsg: 'فقط قم بالتسجيل معنا وسجل دخولك واستمتع بتجربه شراء رائعه',
    skip2BelowMsg: 'ضع كل ماتحتاجه في سله التسوق وعند الانتهاء قم بتأكيد الطلب',
    skip3BelowMsg: 'ضع كل ماتحتاجه في سله التسوق وعند الانتهاء قم بتأكيد الطلب',
    welcomBackMsg: '!مرحبا بعودتك',
    login: 'تسجيل الدخول',
    alreadyHaveAnAccount: 'لديك حساب بالفعل',

    dontHaveAccount: 'ليس لديك حساب ',
    createNewAccount: 'انشاء حساب جديد',
    confirmCreatingNewAccount: 'تأكيد تسجيل حساب جديد',
    registerNow: ' سجل الآن',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    confirmPassword: 'تاكيد كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور',
    forgotPasswordMsg: 'قم بإدخال رقم الهاتف وسوف نقوم بإرسال كود تحقيق اليك',
    resetPassword: 'إعادة تعيين كلمة المرور',
    resetPasswordMsg: 'قم بإنشاء كلمة مرور جديدة',
    setPasswordButton: 'تعيين كلمة المرور',


    enter: 'ادخل',
    sendCode: 'إرسال الكود',
    sendCodeMsg: 'أدخل الكود المكون من 4 ارقام المرسل علي هاتفك',


    phoneNum: 'رقم الهاتف',
    email: 'الايميل',
    city: 'المدينة',
    acceptThsese: 'أوافق علي',
    terms: 'الشروط والأحكام',

    verificationTitle: 'تأكيد تسجيل حساب جديد',
    verificationMsg: 'أدخل الكود المكون من 4 ارقام المرسل علي هاتفك',
    more: 'المزيد',
    orders: 'طلباتي',
    addresses: 'عناويني',
    notifications: 'الاشعارات',
    favourite: 'المفضلة',
    lang: 'اللغة',
    settings: 'الاعدادات',
    contactus: 'اتصل بنا',
    aboutus: 'عن التطبيق',
    shareApp: 'مشاركة التطبيق',
    logout: 'تسجيل الخروج',
    beauty: 'التجميل',
    furniture: 'المطبخ والمنزل',
    shoes: 'الازياء',
    newArrivel: 'وصل حديثا',
    more: 'المزيد',
    product: 'اسم المنتج',
    category: 'كاتيجوري',
    sr100: '١٠٠ رس',
    sectionName: 'اسم السكشن',
    mostImportantStore: 'اهم المتاجر المميزه',
    storeName: 'اسم المتجر',
    rate: 'التصنيف',
    adArea: 'مساحه اعلانيه',
    news: 'كل جديد',
    here: 'هنا',
    homepage: 'تصفح',
    sections: 'الاقسام',
    favourite: 'المفضله',
    busket: 'سله المشتريات',
    search: 'بحث',
    whoarewe: 'من نحن',
    contactus: 'تواصل معنا',
    logout: 'تسجيل الخروج',
    electronicsection: 'قسم الاكترونيات',
    phones: 'هواتف',
    laptop: 'لابتوب',
    desktop: 'ديسكتوب',
    tv: 'تلفيزيون',


    allYouNeed: 'كل اللي تبغاه موجود هنا',
    showAll: 'عرض الكل',
    freeShipping: 'شحن مجاني لمدة 5 ايام',
    fruits: 'فاكهة',
    vegetables: 'خضروات',
    meat: 'لحوم',
    bakes: 'مخبوزات',
    fish: 'أسماك',


    products: 'منتجات',
    watermelon: 'بطيخ',
    strawberry: 'فراولة',
    blackGrape: 'عنب اسود',
    papaya: 'الباباظ',
    oranges: 'برتقال',
    mango: 'مانجا',

    tomatos: 'طماطم',
    cucamber: 'خيار',
    broccoli: 'بروكلي',
    garlic: 'ثوم',
    lemon: 'ليمون',
    lettuc: 'خس',

    bacon: 'لحم مقدد',
    sausage: 'سجق',
    ham: 'لحم مدخن',
    salami: 'شرائح لحم سلامي ',
    steak: 'شريحة لحم ستيك',
    ribs: 'ضلوع',
    beef: 'لحم بفري',


    cookies: 'بسكويت',
    croissant: 'كروسون',
    strudel: 'فطيرة',
    // breadRoll: 'Bread Roll',
    brownBread: 'خبز بني',
    whiteBread: 'خبز ابيض',
    // kolach: 'Kolach',
    fruitCake: 'كيك بالفاكهة',
    doughnut: 'الدونات',
    baguette: 'خبز فرنسي',

    shrimps: 'جمبري',
    tuna: 'تونا',
    salamon: 'سلامون',
    crab: 'سلطعون',
    caviar: 'كافيار',
    sardine: 'سردين',

    voucherMsg: 'خصم خاص جدا لعملائنا علي اشهي أنواع الفراولة تجدها لدينا فقط',
    fresh: 'طازجة',
    bestSelling: 'الأكثر مبيعاَ',
    latestDiscounts: 'أحدث الخصومات',
    latestVouchers: 'أحدث قسائم الخصم',
    discounts: 'الخصومات',
    firstOrderDiscount: 'خصم 10% علي اول طلب',
    subDiscountMsg: 'اجمالي الطلبات +200 ريال',
    code: 'كود',
    useVoucher: 'استخدم القسيمة',

    whatAreYouLookingFor: 'ما الذي تبحث عنه ؟'


} 