export default {
    tamweeny: 'Tamweeny',
    skip: 'skip',
    confirmed: 'confirmed',
    onTheWay: 'On the way',
    delivered: 'Delivered',
    clickHere: 'Click here',
    skip1Msg: 'Log in Easily',
    skip2Msg: 'discover products and Order',
    skip3Msg: 'Track your Order',
    skip1BelowMsg: 'join us and enjoy a wonderful shopping experience',
    skip2BelowMsg: 'Put everything you need in the busket , when done just confirm the order',
    welcomBackMsg: 'Welcome Back!',
    login: 'Log in ',
    alreadyHaveAnAccount: 'Already have an Account',
    dontHaveAccount: "Don't have Account",
    registerNow: 'Register Now',
    createNewAccount: 'Create New Account',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    confirmCreatingNewAccount: 'Confrim Creating New Account',

    forgotPassword: 'Forgot Password',
    forgotPasswordMsg: 'Enter phone Number and we will send you A varification Code',
    resetPassword: 'Reset Password',
    resetPasswordMsg: 'Create New Password',
    setPasswordButton: 'Set As A New Password',
    enter: 'Enter',


    sendCode: 'Send Code',
    sendCodeMsg: 'Enter the 4-digit code that was sent to your phone',
    phoneNum: 'Phone',
    city: 'City',
    email: 'Email',
    acceptThsese: 'Accept thses ',
    terms: 'Terms',

    verificationTitle: 'verify New Account ',
    verificationMsg: 'Enter Code of 4 Digits We Just sent ',
    more: 'More',
    orders: 'My Orders',
    addresses: 'My Addresses',
    notifications: 'Notifications',
    favourite: 'Favourite',
    lang: 'Language',
    settings: 'Settings',
    contactus: 'Contact Us',
    aboutus: 'About Us',
    shareApp: 'Share App',
    logout: 'Log Out',
    skip: 'Skip',
    confirmed: 'Confirmed',
    onTheWay: 'On the Way',
    delivered: 'Delivered',
    loginEasily: 'Log in easily ',
    loginBelowMsg: 'Sign Up and enjoy a wonderful experience ',

    clickHere: 'click here',
    more: 'more',
    product: 'product',
    category: 'category',
    sr100: '100 sr',

    adArea: 'Ad area',
    news: 'news',
    here: 'here',
    homepage: 'home page',
    sections: 'sections',
    busket: 'busket',
    search: 'search',
    whoarewe: 'who are we',
    contactus: 'contact us',
    logout: 'Log Out',

    allYouNeed: 'All you Need is here',
    showAll: 'Show All',
    freeShipping: 'Free Shipping for 5 Days',
    fruits: 'Fruits',
    vegetables: 'Vegetables',
    meat: 'Meat',
    bakes: 'Bakes',
    fish: 'Fish',


    products: 'Products',
    watermelon: 'Watermelon',
    strawberry: 'Strawberry',
    blackGrape: 'Black Grape',
    papaya: 'Papaya',
    oranges: 'Oranges',
    mango: 'Mango',

    tomatos: 'Tomatos',
    cucamber: 'Cucamber',
    broccoli: 'Broccoli',
    garlic: 'Garlic',
    lemon: 'Lemon',
    lettuc: 'lettuce',

    bacon: 'Bacon',
    sausage: 'Sausage',
    ham: 'Ham',
    salami: 'Salami',
    steak: 'Steak',
    ribs: 'Ribs',
    beef: 'Beef',


    cookies: 'Cookies',
    croissant: 'Croissant',
    strudel: 'Strudel',
    // breadRoll: 'Bread Roll',
    brownBread: 'Brown Bread',
    whiteBread: 'White Bread',
    // kolach: 'Kolach',
    fruitCake: 'Fruit Cake',
    doughnut: 'Doughnut',
    baguette: 'Baguette',

    shrimps: 'Shrimps',
    tuna: 'Tuna',
    salamon: 'Salamon',
    crab: 'Crab',
    caviar: 'Caviar',
    sardine: 'Sardine',


    voucherMsg: 'Special discount for any type of strawberries on here ',
    fresh: 'Fresh',
    bestSelling: 'Best Selling',
    latestDiscounts: 'latest Discounts',
    latestVouchers: 'Latest Vouchers',
    firstOrderDiscount: '10% discount for first order',
    discounts: 'Discounts',
    subDiscountMsg: 'Total Orders +200 SR',
    code: 'Code',
    useVoucher: 'Use Voucher',
    whatAreYouLookingFor: 'What Are you Looking For?'







}